name: Release Notice
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":large_blue_circle: HR Staging Portal"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "text": "*$(date +'%d %m %Y')*  |  ${{ github.event.release.tag_name }}",
                      "type": "mrkdwn"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(github.event.release.body) }}
                  }
                }
              ]
            }
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cupcakearmy/confluence-markdown-sync@v1.0.1
        with:
          from: './README.md'
          to: '40861697' # The confluence page id where to write the output
          cloud: mednefits
          user: kenfai@mednefits.com
          token: ${{ secrets.CONFLUENCE }}
