on:
  pull_request:
    types:
      - closed
    branches:
      - 'staging'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":large_blue_circle: HR Staging Portal"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "text": "*${{ github.event.pull_request.merged_at }}*  |  ${{ github.event.pull_request.milestone }}",
                      "type": "mrkdwn"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(github.event.pull_request.body) }}
                  }
                }
              ]
            }
