name: Staging Notice
on:
  pull_request:
    types:
      - closed
    branches:
      - 'staging'
  workflow_dispatch:
jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Get formatted date from runner
        id: formatdate
        run: echo "::set-output name=DATENOW::$(date -d '+8 hour' +'%Y-%m-%d at %H:%M:%S')"
      - name: Send custom JSON data to Slack webhook
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          BODY: _n/a_
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":large_blue_circle: HR Staging Portal"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ steps.formatdate.outputs.DATENOW }} | ${{ github.event.pull_request.title }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(github.event.pull_request.body || env.BODY) }}
                  }
                }
              ]
            }
